(()=>{'use strict';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],clamp=n=>Math.max(0,Math.min(1,n));
$('#year').textContent=new Date().getFullYear();
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const motion=$('#motionMode'),menu=$('#menuToggle'),nav=$('#mobileMenu');
const entry=$('#entryScreen'),enter=$('#enterExperience');document.documentElement.classList.add('entry-locked');function enterSite(){history.replaceState(null,'','#home');window.scrollTo({top:0,left:0,behavior:'instant'});entry.classList.add('is-leaving');document.documentElement.classList.remove('entry-locked');setTimeout(()=>entry.remove(),850);render(0)}enter.addEventListener('click',enterSite);addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&entry.isConnected&&e.target===document.body){e.preventDefault();enterSite()}});
if(menu)menu.setAttribute('aria-controls','mobileMenu');
const typeTargets=all('h1,h2,h3,h4,p,.eyebrow,.section-label,.hero-tags span,.work-meta-bar h3,.work-meta-bar .meta,.name,.role').filter(el=>!el.children.length&&el.textContent.trim()&&!el.closest('.entry-screen'));
const typeObserver=typeof IntersectionObserver!=='undefined'?new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.querySelectorAll('.typing-char').forEach((ch,i)=>{ch.style.transitionDelay=Math.min(i*12,900)+'ms';ch.classList.add('is-visible')});typeObserver.unobserve(entry.target)}),{threshold:.15}):null;
if(!reduced)typeTargets.forEach(el=>{const text=el.textContent;el.textContent='';[...text].forEach(char=>{const span=document.createElement('span');span.className='typing-char';span.textContent=char===' '? '\u00a0':char;el.appendChild(span)});if(typeObserver)typeObserver.observe(el);else el.querySelectorAll('.typing-char').forEach(ch=>ch.classList.add('is-visible'))});
function setMotion(){document.body.classList.toggle('motion-off',reduced);motion.textContent=reduced?'Motion off':'Motion on';motion.setAttribute('aria-pressed',String(reduced));if(reduced)stop();update();}
if(menu&&nav){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-controls','mobileNav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.classList.remove('open');menu.setAttribute('aria-expanded','false');}));}
const hero=$('.hero-lightverse'),tower=$('#towerReveal');tower.classList.add('active');tower.style.setProperty('--reveal-radius','280px');
hero.addEventListener('pointermove',e=>{if(reduced||e.pointerType==='touch')return;const r=hero.getBoundingClientRect();tower.style.setProperty('--reveal-x',((e.clientX-r.left)/r.width*100)+'%');tower.style.setProperty('--reveal-y',((e.clientY-r.top)/r.height*100)+'%');});
const input=$('#projectIdea');all('.idea-chips button').forEach(b=>b.addEventListener('click',()=>{input.value=b.textContent.trim();input.focus();}));
const email='fahadarshadkhantareen@gmail.com';function brief(){const idea=input.value.trim();return 'mailto:'+email+'?subject='+encodeURIComponent('Project enquiry — AKS Creative Agency')+'&body='+encodeURIComponent('Hi Fahad,\n\n'+(idea||'I would like to discuss a creative project.')+'\n\nLocation:\nTimeline:\nBudget:\n');}
$('.console-action').textContent='DISCUSS THIS IDEA ↗';$('.console-action').addEventListener('click',e=>{e.currentTarget.href=brief();});input.addEventListener('keydown',e=>{if(e.key==='Enter')location.href=brief();});
const chapters=[{video:'video/seq-wolf.mp4',title:'From stillness to spectacle.',meta:'01 / WOLF · MOTION STUDY',description:'Scroll to bring the projection to life.',poster:'images/hero-berlin.jpg'},{video:'video/seq-berlin.mp4',title:'Light takes the stage.',meta:'02 / BERLIN · WORLD CHAMPIONSHIP 2019',description:'The Berlin TV Tower competition entry. Awarded second place.',poster:'images/berlin-hero.jpg'},{video:'video/seq-bbbank.mp4',title:'Architecture in motion.',meta:'03 / KARLSRUHE · BBBANK NEWCOMER 2021',description:'A projection journey across the facade of Karlsruhe Palace.',poster:'images/bbbank-hero.jpg'}];
const section=$('#scrollShowMega'),stage=$('.reel-stage'),canvas=$('#reelCanvas'),tabs=all('[data-chapter]');
let progress=0,chapter=0,scheduled=false,playing=false,playStart=0,playProgress=0;
const reelVideos=chapters.map((c,i)=>{const v=document.createElement('video');v.className='reel-video';v.muted=true;v.playsInline=true;v.preload=i===0?'auto':'metadata';v.poster=c.poster;v.setAttribute('aria-label',c.meta);v.src=c.video;v.addEventListener('loadedmetadata',()=>{if(i===chapter)syncVideo();});stage.insertBefore(v,stage.querySelector('.reel-caption'));return v;});
canvas.style.display='none';
function cinematicShift(){stage.classList.remove('chapter-shift');void stage.offsetWidth;stage.classList.add('chapter-shift');setTimeout(()=>stage.classList.remove('chapter-shift'),900)}
function syncVideo(){const v=reelVideos[chapter];if(!v||!Number.isFinite(v.duration)||v.duration<=0)return;const local=Math.min(.99999,progress*3-chapter);const t=local*v.duration;if(Math.abs(v.currentTime-t)>.035){try{v.currentTime=t}catch{}}}
function selectChapter(ci){if(ci===chapter)return;reelVideos[chapter].preload='metadata';chapter=ci;reelVideos[chapter].preload='auto';reelVideos.forEach((v,i)=>v.classList.toggle('is-active',i===chapter));cinematicShift();const c=chapters[ci];$('#reelMeta').textContent=c.meta;$('#reelTitle').textContent=c.title;$('#reelDescription').textContent=c.description;tabs.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===ci)));$('#reelLoading').textContent='';syncVideo();}
function render(p){progress=clamp(p);const ci=Math.min(2,Math.floor(progress*3));if(ci!==chapter)selectChapter(ci);syncVideo();$('#reelProgress').style.width=(progress*100)+'%';}
function update(){scheduled=false;const hr=$('#home').getBoundingClientRect(),hp=clamp(-hr.top/Math.max(1,$('#home').offsetHeight-innerHeight));if(!reduced){$('.lightverse-content').style.transform=`translateY(${-hp*90}px) scale(${1-hp*.12})`;$('.lightverse-content').style.opacity=String(1-hp*.85);tower.style.setProperty('--tower-scale',String(1.04+hp*.32));tower.style.setProperty('--reveal-radius',(280+hp*innerWidth)+'px');}if(!playing&&!reduced){const r=section.getBoundingClientRect();render(clamp(-r.top/(section.offsetHeight-innerHeight)));}}
function schedule(){if(!scheduled){scheduled=true;requestAnimationFrame(update);}}
addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);
tabs.forEach((b,i)=>b.addEventListener('click',()=>{stop();const p=(i+.02)/3;if(reduced)render(p);else window.scrollTo({top:section.offsetTop+(section.offsetHeight-innerHeight)*p,behavior:'smooth'});}));
function stop(){playing=false;$('#playReel').textContent='Play journey';$('#playReel').setAttribute('aria-pressed','false');}
function tick(t){if(!playing)return;const p=Math.min(1,playProgress+(t-playStart)/65000);if(!reduced)window.scrollTo({top:section.offsetTop+(section.offsetHeight-innerHeight)*p,behavior:'instant'});render(p);if(p>=1){stop();return;}requestAnimationFrame(tick);}
$('#playReel').addEventListener('click',()=>{if(playing){stop();return;}playing=true;playProgress=progress>=.99?0:progress;playStart=performance.now();$('#playReel').textContent='Pause journey';$('#playReel').setAttribute('aria-pressed','true');requestAnimationFrame(tick);});
addEventListener('wheel',stop,{passive:true});addEventListener('touchstart',stop,{passive:true});addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','PageDown','PageUp','Escape'].includes(e.key))stop();});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();reelVideos.forEach(v=>v.pause());}});
$('#fullReel').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('.reel-stage').requestFullscreen();}catch{ $('#fullReel').textContent='Fullscreen unavailable';}});document.addEventListener('fullscreenchange',()=>{$('#fullReel').textContent=document.fullscreenElement?'Exit fullscreen':'Fullscreen';});
reelVideos[0].classList.add('is-active');document.getElementById('reelMeta').textContent=chapters[0].meta;document.getElementById('reelTitle').textContent=chapters[0].title;document.getElementById('reelDescription').textContent=chapters[0].description;tabs.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===0)));render(0);all('.work-filter').forEach(b=>{b.setAttribute('aria-pressed',String(b.classList.contains('active')));b.addEventListener('click',()=>{all('.work-filter').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});all('#work .work-item').forEach(item=>{item.classList.toggle('filtered-out',b.dataset.filter!=='all'&&item.dataset.cat!==b.dataset.filter);});});});
const dialog=$('#projectViewer');let gallery=[],imageIndex=0,trigger=null;function showImage(){const img=gallery[imageIndex];$('#viewerImage').src=img.src;$('#viewerImage').alt=img.alt;$('#viewerCount').textContent=`${imageIndex+1} / ${gallery.length}`;$('#prevImage').disabled=gallery.length<2;$('#nextImage').disabled=gallery.length<2;}
function openGallery(el,images,title){trigger=el;gallery=images;imageIndex=0;$('#viewerTitle').textContent=title;showImage();dialog.showModal();document.body.style.overflow='hidden';}
all('.work-card').forEach(card=>{card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label','Explore '+card.querySelector('h3').textContent);const open=()=>openGallery(card,[...card.querySelectorAll('img')],card.querySelector('h3').textContent);card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});});
all('img.lb').filter(img=>!img.closest('.work-card')).forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');img.addEventListener('click',()=>openGallery(img,[img],img.alt));img.addEventListener('keydown',e=>{if(e.key==='Enter')openGallery(img,[img],img.alt);});});
$('#closeViewer').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{document.body.style.overflow='';trigger?.focus({preventScroll:true});});function next(dir){imageIndex=(imageIndex+dir+gallery.length)%gallery.length;showImage();}$('#prevImage').addEventListener('click',()=>next(-1));$('#nextImage').addEventListener('click',()=>next(1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight')next(1);if(e.key==='ArrowLeft')next(-1);});
setMotion();
})();
