(()=>{'use strict';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],clamp=n=>Math.max(0,Math.min(1,n));
$('#year').textContent=new Date().getFullYear();
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,playing=false,progress=0,chapter=0,lastFrame=-1;
const motion=$('#motionMode'),menu=$('#menuToggle'),nav=$('#mobileMenu');
const entry=$('#entryScreen'),enter=$('#enterExperience');document.documentElement.classList.add('entry-locked');function enterSite(){entry.classList.add('is-leaving');document.documentElement.classList.remove('entry-locked');setTimeout(()=>entry.remove(),850)}enter.addEventListener('click',enterSite);addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&entry.isConnected&&e.target===document.body){e.preventDefault();enterSite()}});
if(menu)menu.setAttribute('aria-controls','mobileMenu');
const typeTargets=all('h1,h2,h3,h4,p,.eyebrow,.section-label,.hero-tags span,.work-meta-bar h3,.work-meta-bar .meta,.name,.role').filter(el=>!el.children.length&&el.textContent.trim()&&!el.closest('.entry-screen'));
const typeObserver=typeof IntersectionObserver!=='undefined'?new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.querySelectorAll('.typing-char').forEach((ch,i)=>{ch.style.transitionDelay=Math.min(i*12,900)+'ms';ch.classList.add('is-visible')});typeObserver.unobserve(entry.target)}),{threshold:.15}):null;
if(!reduced)typeTargets.forEach(el=>{const text=el.textContent;el.textContent='';[...text].forEach(char=>{const span=document.createElement('span');span.className='typing-char';span.textContent=char===' '? '\u00a0':char;el.appendChild(span)});if(typeObserver)typeObserver.observe(el);else el.querySelectorAll('.typing-char').forEach(ch=>ch.classList.add('is-visible'))});
function setMotion(){document.body.classList.toggle('motion-off',reduced);motion.textContent=reduced?'Motion off':'Motion on';motion.setAttribute('aria-pressed',String(reduced));if(reduced)stop();update();}
if(menu&&nav){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-controls','mobileNav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.classList.remove('open');menu.setAttribute('aria-expanded','false');}));}
const hero=$('.hero-lightverse'),tower=$('#towerReveal');tower.classList.add('active');tower.style.setProperty('--reveal-radius','280px');
hero.addEventListener('pointermove',e=>{if(reduced||e.pointerType==='touch')return;const r=hero.getBoundingClientRect();tower.style.setProperty('--reveal-x',((e.clientX-r.left)/r.width*100)+'%');tower.style.setProperty('--reveal-y',((e.clientY-r.top)/r.height*100)+'%');});
const input=$('#projectIdea');all('.idea-chips button').forEach(b=>b.addEventListener('click',()=>{input.value=b.textContent.trim();input.focus();}));
const email='fahadarshadkhantareen@gmail.com';function brief(){const idea=input.value.trim();return 'mailto:'+email+'?subject='+encodeURIComponent('Project enquiry — AKS Creative Agency')+'&body='+encodeURIComponent('Hi Fahad,\n\n'+(idea||'I would like to discuss a creative project.')+'\n\nLocation:\nTimeline:\nBudget:\n');}
$('.console-action').textContent='DISCUSS THIS IDEA ↗';$('.console-action').addEventListener('click',e=>{e.currentTarget.href=brief();});input.addEventListener('keydown',e=>{if(e.key==='Enter')location.href=brief();});
const chapters=[{folder:'sequence-wolf',count:267,title:'From stillness to spectacle.',meta:'01 / WOLF · MOTION STUDY',description:'Scroll to bring the projection to life.',poster:'images/hero-berlin.jpg'},{folder:'sequence',count:320,title:'Light takes the stage.',meta:'02 / BERLIN · WORLD CHAMPIONSHIP 2019',description:'The Berlin TV Tower competition entry. Awarded second place.',poster:'images/berlin-hero.jpg'},{folder:'sequence-bbbank',count:248,title:'Architecture in motion.',meta:'03 / KARLSRUHE · BBBANK NEWCOMER 2021',description:'A projection journey across the facade of Karlsruhe Palace.',poster:'images/bbbank-hero.jpg'},{folder:'sequence-japan',count:316,title:'A wave. A new world.',meta:'04 / JAPAN-THEMED SHOW',description:'The Great Wave and rising sun, reimagined at monumental scale.',poster:'images/japan-hero.jpg'}];
const section=$('#scrollShowMega'),canvas=$('#reelCanvas'),ctx=canvas.getContext('2d'),tabs=all('[data-chapter]'),cache=new Map(),queue=[],pending=new Set();let active=0,targetKey='',lastImage=null,scheduled=false;
function path(ci,fi){return chapters[ci].folder+'/frame_'+String(fi).padStart(4,'0')+'.jpg';}
function draw(img){if(!img||!img.naturalWidth)return;lastImage=img;const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}const scale=Math.min(canvas.width/img.naturalWidth,canvas.height/img.naturalHeight);ctx.fillStyle='#050608';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,(canvas.width-img.naturalWidth*scale)/2,(canvas.height-img.naturalHeight*scale)/2,img.naturalWidth*scale,img.naturalHeight*scale);}
function pump(){while(active<5&&queue.length){const key=queue.shift();active++;const img=new Image();img.onload=()=>{cache.set(key,img);pending.delete(key);active--;if(key===targetKey){draw(img);$('#reelLoading').textContent='';}while(cache.size>110){const old=cache.keys().next().value;cache.delete(old);}pump();};img.onerror=()=>{pending.delete(key);active--;if(key===targetKey)$('#reelLoading').textContent='Frame unavailable — keep scrolling';pump();};img.src=key;}}
function load(key,priority=false){if(cache.has(key))return;if(pending.has(key)){if(priority){const i=queue.indexOf(key);if(i>=0){queue.splice(i,1);queue.unshift(key);}}return;}pending.add(key);priority?queue.unshift(key):queue.push(key);pump();}
function render(p){progress=clamp(p);const ci=Math.min(3,Math.floor(progress*4)),local=Math.min(.99999,progress*4-ci),fi=Math.min(chapters[ci].count-1,Math.floor(local*chapters[ci].count));if(ci!==chapter||lastFrame===-1){chapter=ci;const c=chapters[ci];$('#reelMeta').textContent=c.meta;$('#reelTitle').textContent=c.title;$('#reelDescription').textContent=c.description;tabs.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===ci)));lastImage=null;const poster=new Image();poster.onload=()=>{if(chapter===ci&&!cache.has(targetKey))draw(poster);};poster.src=c.poster;}
$('#reelProgress').style.width=(progress*100)+'%';if(fi===lastFrame&&targetKey===path(ci,fi))return;lastFrame=fi;targetKey=path(ci,fi);if(cache.has(targetKey)){draw(cache.get(targetKey));$('#reelLoading').textContent='';}else{load(targetKey,true);$('#reelLoading').textContent='Loading frame…';}for(let offset=1;offset<=9;offset++){if(fi+offset<chapters[ci].count)load(path(ci,fi+offset));if(fi-offset>=0)load(path(ci,fi-offset));}}
function update(){scheduled=false;const hr=$('#home').getBoundingClientRect(),hp=clamp(-hr.top/Math.max(1,$('#home').offsetHeight-innerHeight));if(!reduced){$('.lightverse-content').style.transform=`translateY(${-hp*90}px) scale(${1-hp*.12})`;$('.lightverse-content').style.opacity=String(1-hp*.85);tower.style.setProperty('--tower-scale',String(1.04+hp*.32));tower.style.setProperty('--reveal-radius',(280+hp*innerWidth)+'px');}if(!playing&&!reduced){const r=section.getBoundingClientRect();render(clamp(-r.top/(section.offsetHeight-innerHeight)));}}
function schedule(){if(!scheduled){scheduled=true;requestAnimationFrame(update);}}
addEventListener('scroll',schedule,{passive:true});addEventListener('resize',()=>{if(lastImage)draw(lastImage);schedule();});
tabs.forEach((b,i)=>b.addEventListener('click',()=>{stop();const p=(i+.02)/4;if(reduced)render(p);else window.scrollTo({top:section.offsetTop+(section.offsetHeight-innerHeight)*p,behavior:'smooth'});}));
let playStart=0,playProgress=0;function stop(){playing=false;$('#playReel').textContent='Play journey';$('#playReel').setAttribute('aria-pressed','false');}
function tick(t){if(!playing)return;const p=Math.min(1,playProgress+(t-playStart)/65000);if(!reduced)window.scrollTo({top:section.offsetTop+(section.offsetHeight-innerHeight)*p,behavior:'instant'});render(p);if(p>=1){stop();return;}requestAnimationFrame(tick);}
$('#playReel').addEventListener('click',()=>{if(playing){stop();return;}playing=true;playProgress=progress>=.99?0:progress;playStart=performance.now();$('#playReel').textContent='Pause journey';$('#playReel').setAttribute('aria-pressed','true');requestAnimationFrame(tick);});
addEventListener('wheel',stop,{passive:true});addEventListener('touchstart',stop,{passive:true});addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','PageDown','PageUp','Escape'].includes(e.key))stop();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
$('#fullReel').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('.reel-stage').requestFullscreen();}catch{ $('#fullReel').textContent='Fullscreen unavailable';}});document.addEventListener('fullscreenchange',()=>{$('#fullReel').textContent=document.fullscreenElement?'Exit fullscreen':'Fullscreen';if(lastImage)draw(lastImage);});
motion.addEventListener('click',()=>{reduced=!reduced;setMotion();});
all('.work-filter').forEach(b=>{b.setAttribute('aria-pressed',String(b.classList.contains('active')));b.addEventListener('click',()=>{all('.work-filter').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});all('#work .work-item').forEach(item=>{item.classList.toggle('filtered-out',b.dataset.filter!=='all'&&item.dataset.cat!==b.dataset.filter);});});});
const dialog=$('#projectViewer');let gallery=[],imageIndex=0,trigger=null;function showImage(){const img=gallery[imageIndex];$('#viewerImage').src=img.src;$('#viewerImage').alt=img.alt;$('#viewerCount').textContent=`${imageIndex+1} / ${gallery.length}`;$('#prevImage').disabled=gallery.length<2;$('#nextImage').disabled=gallery.length<2;}
function openGallery(el,images,title){trigger=el;gallery=images;imageIndex=0;$('#viewerTitle').textContent=title;showImage();dialog.showModal();document.body.style.overflow='hidden';}
all('.work-card').forEach(card=>{card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label','Explore '+card.querySelector('h3').textContent);const open=()=>openGallery(card,[...card.querySelectorAll('img')],card.querySelector('h3').textContent);card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});});
all('img.lb').filter(img=>!img.closest('.work-card')).forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');img.addEventListener('click',()=>openGallery(img,[img],img.alt));img.addEventListener('keydown',e=>{if(e.key==='Enter')openGallery(img,[img],img.alt);});});
$('#closeViewer').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{document.body.style.overflow='';trigger?.focus({preventScroll:true});});function next(dir){imageIndex=(imageIndex+dir+gallery.length)%gallery.length;showImage();}$('#prevImage').addEventListener('click',()=>next(-1));$('#nextImage').addEventListener('click',()=>next(1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight')next(1);if(e.key==='ArrowLeft')next(-1);});
setMotion();render(0);
})();
